### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by oaoak** [Kongkawee/ku-polls#56]
1. Consider using one file for the Questions and Choices data, and a separate file for the votes data. This way, you can create a new installation that has poll questions but no votes. A real deployment would not include your demo users, so it would not include their votes, either.

2. There could be a signup or login button in both signup and login pages.

**Comment by Kongkawee** [comment]
Thanks for reviews, I will fix it.

**Comment by Kongkawee** [comment]
Problem solved.
